### ISSUE TITLE
WORK ON `Overall Grade` and YAML Structure

### ISSUE THREAD

**Issue by andrewpbray** [gradebook-dev/gradebook-app#94]
Currently, in the R package, the calculation of the Overall Grade is handled separately from other categories and computed after the main calculations in `get_grades()` are complete. The package will be updated to an alternative structure where Overall Grade can be put at the top of the tree and act like any other category. See examples below.

```yaml
# Current
categories:
  - category: Homework
    aggregation: equally_weighted
    assignments:
      - "Homework 1"
      - "Homework 2"
  - category: Midterm
    aggregation: none
    assignments:
      - "Midterm Exam"
  - category: Final
    aggregation: none
    assignments:
      - "Final Exam"
  - category: Overall Grade
    aggregation: weighted_mean
    weights: 
    - 0.20
    - 0.40
    - 0.40
    assignments:
      - "Homework"
      - "Midterm"
      - "Final"

# Alt
categories:
  category: Overall Grade
  aggregation: weighted_mean
  assignments:
    - category: Homework
      weight: 0.20
      aggregation: equally_weighted
      assignments:
        - "Homework 1"
        - "Homework 2"
    - category: Midterm
      weight: 0.40
      aggregation: none
      assignments:
        - "Midterm Exam"
    - category: Final
      weight: 0.40
      aggregation: none
      assignments:
        - "Final Exam"
```
The app should be updated to account for this change. It will involve:

- [x] Set up so that it appears with a default overall Grade category set to weighted mean.

- [x] drops do not work -- do not show up in modal or UI after category creation & do not safe in YAML.
- [x] Rename key from weights to `weight`
- [x] make sure `Overall Grade` category does not work in UI

- [x] Set up so that it appears with a default overall Grade category set to weighted mean

See [companion issue](https://github.com/gradebook-dev/gradebook/issues/42) in package repo.
